{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"TLDataSummary\",\"Last Refresh Date\",\"XREF_DealerGrps\",\"ZipCode_SQLDb\",\"List of All U S  Counties and Cities\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.751.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "da12080e-419c-49ad-b808-1fbb93930aa0",
        "fromColumn": "Sale_Date",
        "fromTable": "TLDataSummary",
        "toColumn": "Date",
        "toTable": "DateCalendar"
      },
      {
        "name": "051cce81-c23f-4eec-926b-0b19efc04a1d",
        "fromColumn": "Rooftop_Zip",
        "fromTable": "TLDataSummary",
        "isActive": false,
        "toColumn": "Zip_Code",
        "toTable": "ZipCode_SQLDb"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "TLDataSummary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Rec_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef9392d0-123b-48d4-8b4c-f1d295ce06c5",
            "sourceColumn": "Rec_id",
            "summarizeBy": "sum"
          },
          {
            "name": "SaleYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce4e7819-f30a-4618-86f0-053512d3d984",
            "sourceColumn": "SaleYear",
            "summarizeBy": "sum"
          },
          {
            "name": "SaleYearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be7dfd72-b986-49d7-93d5-4a006289feb1",
            "sourceColumn": "SaleYearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "Administrator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0166bc16-3771-4520-9e9e-7d3f44c8648a",
            "sourceColumn": "Administrator",
            "summarizeBy": "none"
          },
          {
            "name": "DataSource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"TLDataSummary\",\"TableItemName\":\"DataSource (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecf25760-966a-48e1-8a58-03a674792e17",
            "sourceColumn": "DataSource",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9d4ee44-f386-48ba-b8b7-a42482aaca46",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "DealerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5132079b-447e-41c1-b1c1-4087ce607b34",
            "sourceColumn": "DealerName",
            "summarizeBy": "none"
          },
          {
            "name": "Agent_Group_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0929866-78bd-4b26-84bf-bc21aeb35b32",
            "sourceColumn": "Agent_Group_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Dealer_Group_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9df9b04a-e9ba-4fd0-a1ea-83f2f0359cbf",
            "sourceColumn": "Dealer_Group_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e33a49d2-b5fc-4810-adbb-1b3863a20983",
            "sourceColumn": "Rooftop_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_Addr_Updated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2662b0ea-807e-48d8-a6b1-4fd05c2f183f",
            "sourceColumn": "Rooftop_Addr_Updated",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ace451e4-4c86-43e1-8157-8b15fe4116fa",
            "sourceColumn": "Rooftop_City",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f934e23-d07d-4145-b4b0-75c9bd2f87e7",
            "sourceColumn": "Rooftop_State",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_Zip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe7bf6f3-e19c-491d-a155-ebff998650db",
            "sourceColumn": "Rooftop_Zip",
            "summarizeBy": "none"
          },
          {
            "name": "Franchise_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"TLDataSummary\",\"TableItemName\":\"Franchise-v-Non\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f6ddaa4-1b1d-4945-9f32-b3c6a3d78843",
            "sourceColumn": "Franchise_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f751568-10cb-465e-b402-c0552974957e",
            "sourceColumn": "Sales_Rep",
            "summarizeBy": "none"
          },
          {
            "name": "Flag_Bank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3f05e9ec-b580-4680-922b-56dab31b4ced",
            "sourceColumn": "Flag_Bank",
            "summarizeBy": "none"
          },
          {
            "name": "Flag_Credit_Union",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "23dd459b-6853-4b9c-898f-e15ad919386a",
            "sourceColumn": "Flag_Credit_Union",
            "summarizeBy": "none"
          },
          {
            "name": "Flag_Refinance_Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f3e35a14-816d-49bd-ba24-d729a9b88e26",
            "sourceColumn": "Flag_Refinance_Company",
            "summarizeBy": "none"
          },
          {
            "name": "Common_Product_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "462cabb1-c459-461e-9477-767e649a4476",
            "sourceColumn": "Common_Product_Group",
            "summarizeBy": "none"
          },
          {
            "name": "Common_Product_Group_Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bae9c8c4-baa9-42ba-85b6-b3c6f9b04627",
            "sourceColumn": "Common_Product_Group_Description",
            "summarizeBy": "none"
          },
          {
            "name": "Product_Grouping_Pricing_Cancel_Analysis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc0047c2-eb14-436a-9a0f-debdab861d49",
            "sourceColumn": "Product_Grouping_Pricing_Cancel_Analysis",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionTypeDesc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ed1a507-85df-45df-be62-21fd72a16607",
            "sourceColumn": "TransactionTypeDesc",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be159d9e-6561-4937-81ce-59ef9a2fa1ad",
            "sourceColumn": "Revenue_Type",
            "summarizeBy": "none"
          },
          {
            "name": "SalesChannel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "522c9d09-7d8c-4ef5-9a9c-51ba19ed90ae",
            "sourceColumn": "SalesChannel",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d295d4dc-28d6-4910-a485-54f6cd5adfc6",
            "sourceColumn": "Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "ContractCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "be52c4b3-4ee5-41a0-a0e2-4e30e7bb1527",
            "sourceColumn": "ContractCount",
            "summarizeBy": "sum"
          },
          {
            "name": "dtupdate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "48d3fe82-8dc6-4bbf-bf4e-b3cb874f44c1",
            "sourceColumn": "dtupdate",
            "summarizeBy": "none"
          },
          {
            "name": "Sale_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d3f00c3c-dbda-481f-97d9-c34386752f49",
            "sourceColumn": "Sale_Date",
            "summarizeBy": "none"
          },
          {
            "name": "End_Market",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a08bc881-7c5c-48f4-bc5a-c5f6eaea5c46",
            "sourceColumn": "End_Market",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              " Nextday(Dateadd(DateCalendar[Date],-12,Month)",
              ")"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "9836d55a-74e3-42a1-9cd4-360160f0eb29",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "Lastdate(TLDataSummary[Sale_Date])"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "af9b0f4a-3446-4a95-84f0-f4059c8c9199",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BusinessUnit_Adjusted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ada779b6-bda9-47e1-8740-736f25589e21",
            "sourceColumn": "BusinessUnit_Adjusted",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue_Type_Adjusted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b19a4418-2249-4d97-afd1-19ab3e6751c1",
            "sourceColumn": "Revenue_Type_Adjusted",
            "summarizeBy": "none"
          },
          {
            "name": "FlagRevenue_Ttl_PreAcq_Diligence_Adj",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64351fea-5ec0-430d-af7b-0be0680bba8f",
            "sourceColumn": "FlagRevenue_Ttl_PreAcq_Diligence_Adj",
            "summarizeBy": "none"
          },
          {
            "name": "FlagRevenue_Ttl_PreAcq_Diligence_Adj_Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20fd15ab-4bca-4501-9c18-3e1bd9293a79",
            "sourceColumn": "FlagRevenue_Ttl_PreAcq_Diligence_Adj_Reason",
            "summarizeBy": "none"
          },
          {
            "name": "FlagRevenue_Propel_Revenue_Analysis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cd40d03-276e-46c9-b04b-57256db49b7d",
            "sourceColumn": "FlagRevenue_Propel_Revenue_Analysis",
            "summarizeBy": "none"
          },
          {
            "name": "FlagRevenue_Propel_Revenue_Analysis_Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb2908f4-b577-42b0-8855-79265bc7fe0f",
            "sourceColumn": "FlagRevenue_Propel_Revenue_Analysis_Reason",
            "summarizeBy": "none"
          },
          {
            "name": "FlagRevenue_Propel_Pricing_Analysis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "030dde1e-55c6-47d4-995e-921b945bf282",
            "sourceColumn": "FlagRevenue_Propel_Pricing_Analysis",
            "summarizeBy": "none"
          },
          {
            "name": "FlagRevenue_Propel_Pricing_Analysis_Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ef0714d-ee3e-41b9-bbe7-82eccca7b073",
            "sourceColumn": "FlagRevenue_Propel_Pricing_Analysis_Reason",
            "summarizeBy": "none"
          },
          {
            "name": "ConversionFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54547205-5c48-46ee-9b17-89e009c0c391",
            "sourceColumn": "ConversionFlag",
            "summarizeBy": "none"
          },
          {
            "name": "YRLY_RoofTopSize",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fa6468d-8c67-4119-a15a-d62af19cbb0e",
            "sourceColumn": "YRLY_RoofTopSize",
            "summarizeBy": "none"
          },
          {
            "name": "LTM_RoofTopSize",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "647f93b1-448d-4c6a-b3b2-b058f3a10d40",
            "sourceColumn": "LTM_RoofTopSize",
            "summarizeBy": "none"
          },
          {
            "name": "ContractCount_original",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9edd3a85-bb7b-4d4a-976f-dbf58bff76bb",
            "sourceColumn": "ContractCount_original",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rep_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa8f2eba-9abe-495e-a5f1-3ac76c2dbd94",
            "sourceColumn": "Sales_Rep_1",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d142c4e3-603f-4dd4-923c-0ee37249089c",
            "sourceColumn": "Sales_Rep_2",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e88a7a77-36ec-4adc-be26-bfd9dd7d05c7",
            "sourceColumn": "Sales_Rep_3",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5ea91a0-4b5b-400f-bc53-bff83a492fa7",
            "sourceColumn": "Sales_Rep_4",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_1_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cadaeb18-ba9d-4a1a-a420-ca3e35dc3dc1",
            "sourceColumn": "Sales_Rep_1_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rep_2_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "472dffe7-eaa1-463e-8e8c-001af3553405",
            "sourceColumn": "Sales_Rep_2_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rep_3_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "13265d50-6066-464f-80ec-6dcccff7e968",
            "sourceColumn": "Sales_Rep_3_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rep_4_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b1eed48d-8777-4f1c-8223-6ca94d5969f1",
            "sourceColumn": "Sales_Rep_4_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Area_Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83e70558-c2d9-4d59-a635-a5501fe7a9ad",
            "sourceColumn": "Area_Director",
            "summarizeBy": "none"
          },
          {
            "name": "Regional_Vice_President",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76335774-1e7c-4d7a-8d6c-b5e185ba4cf2",
            "sourceColumn": "Regional_Vice_President",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "851b3287-1655-456a-85a9-a032a6eed544",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Active_Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ede7415-f39e-49e8-8074-4efea4138619",
            "sourceColumn": "Sales_Active_Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Franchise-v-Non",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"t\",\"Entity\":\"TLDataSummary\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Franchise_Desc\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Franchise\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Franchise_Desc\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Franchise'\"}}]]}}},{\"DisplayName\":\"Non-Franchise\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Franchise_Desc\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Credit Union / Bank / Refi / Other'\"}}],[{\"Literal\":{\"Value\":\"'Non Franchise'\"}}],[{\"Literal\":{\"Value\":\"'Unknown'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('TLDataSummary'[Franchise_Desc]),",
              "\t\"(Blank)\",",
              "\t'TLDataSummary'[Franchise_Desc] IN {\"Franchise\"},",
              "\t\"Franchise\",",
              "\t'TLDataSummary'[Franchise_Desc] IN {\"Credit Union / Bank / Refi / Other\",",
              "\t\t\"Non Franchise\",",
              "\t\t\"Unknown\"},",
              "\t\"Non-Franchise\",",
              "\t'TLDataSummary'[Franchise_Desc]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "TLDataSummary"
                          }
                        },
                        "Property": "Franchise_Desc"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "bc056530-99fc-4bb4-a349-16e120982eb9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2e9f5b3-b680-4908-9b9f-7c94333f9614",
            "sourceColumn": "territory",
            "summarizeBy": "none"
          },
          {
            "name": "DataSource (groups)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"t\",\"Entity\":\"TLDataSummary\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"DataSource\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"APCO Channels\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"DataSource\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'D365'\"}}]]}}},{\"DisplayName\":\"NAC Channels\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"DataSource\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'COMMISSION STATEMENTS'\"}}],[{\"Literal\":{\"Value\":\"'EKB'\"}}],[{\"Literal\":{\"Value\":\"'EKB-NAC'\"}}],[{\"Literal\":{\"Value\":\"'FDAC'\"}}],[{\"Literal\":{\"Value\":\"'GAP and TotalRestart'\"}}],[{\"Literal\":{\"Value\":\"'NAC Finance'\"}}],[{\"Literal\":{\"Value\":\"'NetSuite'\"}}],[{\"Literal\":{\"Value\":\"'P&L Expenses'\"}}],[{\"Literal\":{\"Value\":\"'RPA_History'\"}}],[{\"Literal\":{\"Value\":\"'SCS'\"}}],[{\"Literal\":{\"Value\":\"'UTP'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('TLDataSummary'[DataSource]),",
              "\t\"(Blank)\",",
              "\t'TLDataSummary'[DataSource] IN {\"D365\"},",
              "\t\"APCO Channels\",",
              "\t'TLDataSummary'[DataSource] IN {\"COMMISSION STATEMENTS\",",
              "\t\t\"EKB\",",
              "\t\t\"EKB-NAC\",",
              "\t\t\"FDAC\",",
              "\t\t\"GAP and TotalRestart\",",
              "\t\t\"NAC Finance\",",
              "\t\t\"NetSuite\",",
              "\t\t\"P&L Expenses\",",
              "\t\t\"RPA_History\",",
              "\t\t\"SCS\",",
              "\t\t\"UTP\"},",
              "\t\"NAC Channels\",",
              "\t'TLDataSummary'[DataSource]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "TLDataSummary"
                          }
                        },
                        "Property": "DataSource"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a77002a9-3538-4e52-a5b3-8707defca962",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "zip_lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Latitude",
            "dataType": "double",
            "lineageTag": "af832d8b-36d9-4cab-9f7e-4c70b9d5883a",
            "sourceColumn": "zip_lat",
            "summarizeBy": "none"
          },
          {
            "name": "zip_long",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Longitude",
            "dataType": "double",
            "lineageTag": "61cac5cf-037d-47b0-8e6b-20691a60d8ae",
            "sourceColumn": "zip_long",
            "summarizeBy": "none"
          },
          {
            "name": "DealerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74a8fac3-c03b-4248-a882-0ec3f1c8099a",
            "sourceColumn": "DealerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Region_Corrected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(",
              "    TLDataSummary[Rooftop_State] IN {\"WA\",\"OR\",\"CA\",\"ID\",\"MT\",\"WY\",\"NV\",\"AZ\",\"UT\"}, \"WEST\",",
              "    IF(TLDataSummary[Rooftop_State] IN {\"CO\",\"NM\",\"OK\",\"TX\",\"AR\",\"LA\"}, \"SOUTH CENTRAL\",",
              "    IF(TLDataSummary[Rooftop_State] IN {\"AL\",\"MS\",\"GA\",\"FL\",\"SC\",\"NC\"}, \"SOUTH EAST\",",
              "    IF(TLDataSummary[Rooftop_State] IN {\"AR\",\"MO\",\"KS\",\"NE\",\"SD\",\"ND\",\"MN\",\"WI\",\"IL\",\"IA\"}, \"NORTH CENTRAL\", \"NORTH EAST\"))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2bf04247-145f-414c-8fba-9e9b800cb49e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "#Rooftop_per_Sales_Rep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'TLDataSummary'[Rooftop_State] & \": \" &",
              "ROUND(CALCULATE(",
              "    DISTINCTCOUNT(TLDataSummary[Rooftop_Name])/DISTINCTCOUNT(TLDataSummary[Sales_Rep_1]),",
              "    ALLEXCEPT('TLDataSummary','TLDataSummary'[Rooftop_State])),0)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4c443e1a-cd58-4cc0-9984-3a2ed36433be",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f45d30c8-82ac-4662-b5a7-e22d1b400604",
        "measures": [
          {
            "name": "Commission Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "calculate(sum(TLDataSummary[Revenue]),TLDataSummary[Revenue_Type] =\"Commission Revenue\")",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "87420568-76f8-4282-8c47-6d3657448fc0"
          },
          {
            "name": "Admin Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sum(TLDataSummary[Revenue]),TLDataSummary[Revenue_Type] =\"Admin Fee\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "38cd4c59-703a-4c7e-8a3f-0f885637632f"
          },
          {
            "name": "PY Admin Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "Calculate([Admin Revenue],SAMEPERIODLASTYEAR('DateCalendar'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2a3fe428-3035-4d71-91f2-e1d9e0fac0b4"
          },
          {
            "name": "PY Commission Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "Calculate([Commission Revenue],SAMEPERIODLASTYEAR('DateCalendar'[Date]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0c08dc42-2797-4431-9398-c06fd91b6100"
          },
          {
            "name": "PY Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "Calculate([Total Revenue],DATEADD(DateCalendar[Date],-12,MONTH))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "44694c49-0cc5-4021-ba04-da34bc6ede3b"
          },
          {
            "name": "YOY Revenue % Change",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "Divide([YOY Revenue Variance],[PY Revenue])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cebe2e03-01c9-4dba-9111-8f50408a6d73"
          },
          {
            "name": "Revenue divided by PY Revenue",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "(DIVIDE(SUM('TLDataSummary'[Revenue]), [PY Revenue]))"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalDivision",
                  "version": 0
                }
              }
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "5ba135a0-51a7-4dc5-b90f-6032a87c9869"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "sum(TLDataSummary[Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4e3da0fa-d74e-4af1-bc51-87d14f7138a8"
          },
          {
            "name": "YOY Revenue Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "If(isblank([PY Revenue]),BLANK(),[Total Revenue]-[PY Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "22bff04f-f308-416c-97cf-3fff380396d0"
          },
          {
            "name": "Dealer Count",
            "expression": "DISTINCTCOUNTNOBLANK(TLDataSummary[Dealer_Group_Name])",
            "formatString": "#,0",
            "lineageTag": "848a0bab-6bc8-4dda-b8fe-42a63ea9dc6a"
          },
          {
            "name": "Rooftop Count",
            "expression": "DISTINCTCOUNT(TLDataSummary[Rooftop_Name])",
            "formatString": "#,0",
            "lineageTag": "3c6b3495-cdfa-46b8-b70d-deac797af57e"
          },
          {
            "name": "Revenue Per Rooftop",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "Divide([Total Revenue],[Rooftop Count],blank())",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7bf3cd72-8a6a-47ef-b4f0-7a18488707b2"
          },
          {
            "name": "Total Gross Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "Calculate(Sum(TLDataSummary[Revenue]),TLDataSummary[TransactionTypeDesc]=\"Activation\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "65957ab2-2a54-4324-a7af-6d95d247accd"
          },
          {
            "name": "Revenue Per Contract",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "Divide([Total Gross Revenue],[Contract_Count])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c8d18ad3-0a5f-4b94-837e-bb36eed0b837"
          },
          {
            "name": "Contract_Count",
            "expression": "sum(TLDataSummary[ContractCount])",
            "formatString": "#,0",
            "lineageTag": "650b33fb-9255-4a17-a0a1-abc48ba005c1"
          },
          {
            "name": "Consolidated Revenue (Cancellations)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "Calculate([Total Revenue],TLDataSummary[TransactionTypeDesc] =\"Cancellation\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "9bebc4dd-a890-464c-a121-3f5730d9a112"
          },
          {
            "name": "Cancels As % of Gross Revenue",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "Divide(ABS([Consolidated Revenue (Cancellations)]),[Total Gross Revenue])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a1a19582-6c80-4712-9d8b-180d8966aa8f"
          },
          {
            "name": "Rolling 12 Revenue (NAC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "var startday = Nextday(Lastdate(Dateadd(DateCalendar[Date],-12,Month)))",
              "",
              "var endday = Lastdate(TLDataSummary[Sale_Date])",
              "",
              "return",
              "",
              "Calculate([Total Revenue],DATESBETWEEN(DateCalendar[Date],startday,endday))",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7b3395f6-a8b1-4e3c-bb18-f06392e6b268"
          },
          {
            "name": "LTM Revenue (P32)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESINPERIOD(DateCalendar[Date], MAX(DateCalendar[Date]), -12, MONTH)",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d52f30c4-4467-4014-aa88-f89d3df683ba"
          },
          {
            "name": "LTM Revenue V2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "VAR EndDate = MAX(DateCalendar[Date])",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate)",
              ")",
              "",
              "RETURN",
              "    Result +0"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "96890975-5f8b-44cb-baae-ed7928310ef3"
          },
          {
            "name": "LTM Revenue (Completed Months)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "VAR EndDate = EOMONTH(MAX(DateCalendar[Date]),-1)",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate)",
              ")",
              "",
              "RETURN",
              "    Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a95f4e3b-b166-4ad2-8b7f-21450a627eb3"
          },
          {
            "name": "New Customer Revenue",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]=0 && [Total Revenue]>0, [Total Revenue],0))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8d33889a-e45b-41c0-8474-951b1b5062b5"
          },
          {
            "name": "New Customer Rooftop Count",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]=0 && [Total Revenue]>0, 1,0))",
            "formatString": "0",
            "lineageTag": "bf17ad20-6f33-4924-aa9e-c5b58a8012ca"
          },
          {
            "name": "Non-Producers Count",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]<=0 && [Total Revenue]<=0, 1,0))",
            "formatString": "0",
            "lineageTag": "26f1115b-29ae-47d2-985d-257bb6fb6102"
          },
          {
            "name": "Non-Producers Revenue",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]<=0 && [Total Revenue]<=0, [Total Revenue],0))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5343bdf3-06e1-4996-b558-119e1e7a275f"
          },
          {
            "name": "Retained Customer Count",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]>0 && [Total Revenue]>0, 1,0))",
            "formatString": "0",
            "lineageTag": "77dcd488-1aab-4544-b3bc-19d600819652"
          },
          {
            "name": "Retained Customer Incremental Revenue",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]>0 && [Total Revenue]>0, [Total Revenue]-[PY Revenue],0))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "699ed350-a72d-4905-8799-a5cec91e7acc"
          },
          {
            "name": "Lost Customer Count",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]>0 && [Total Revenue]<=0, 1,0))",
            "formatString": "0",
            "lineageTag": "8110a6f9-a9d6-4168-8435-14a9965e320a"
          },
          {
            "name": "Lost Customer Revenue Lost",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]>0 && [Total Revenue]<=0, [PY Revenue],0))*-1",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "fbc6e157-44d0-4f22-af34-b940c9da2ca3"
          },
          {
            "name": "Calculated Revenue Bridge",
            "expression": "[New Customer Revenue]+[Lost Customer Revenue Lost]+[Retained Customer Incremental Revenue]+[Non-Producers Revenue]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ee69d318-0d68-4eec-8fff-c468298a1c1a"
          },
          {
            "name": "Calculated Current Revenue",
            "expression": "[PY Revenue]+[Calculated Revenue Bridge]+[Lost Customer Current Revenue Impact]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2cf9360c-de14-4416-9e64-f8b30d584483"
          },
          {
            "name": "Calculated Revenue Variance",
            "expression": "[Calculated Current Revenue]-[Total Revenue]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "94cabc4e-ee60-4c04-a173-2cf3c4457638"
          },
          {
            "name": "Lost Customer Current Revenue Impact",
            "expression": "sumx(values(TLDataSummary[Rooftop_Name]),if([PY Revenue]>0 && [Total Revenue]<=0, [Total Revenue],0))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "66b90f2e-f6b2-4618-a240-e55249be1e39"
          },
          {
            "name": "LTM Admin Revenue",
            "expression": [
              "",
              "",
              "VAR EndDate = MAX(DateCalendar[Date])",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate),TLDataSummary[Revenue_Type] = \"Admin Fee\"",
              "    ",
              ")",
              "",
              "RETURN",
              "    Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "14127bcf-ec47-4256-99e6-48a8e5de03f0"
          },
          {
            "name": "LTM Commission Revenue",
            "expression": [
              "",
              "",
              "VAR EndDate = MAX(DateCalendar[Date])",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate),TLDataSummary[Revenue_Type] = \"Commission Revenue\"",
              "    ",
              ")",
              "",
              "RETURN",
              "    Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0c9480ef-dcc7-4ca9-aec7-007c0de751bc"
          },
          {
            "name": "Contract Count_Admin",
            "expression": "calculate(sum(TLDataSummary[ContractCount]),TLDataSummary[Revenue_Type]=\"admin fee\")",
            "formatString": "0",
            "lineageTag": "bc1da5a1-aae1-4752-9012-087ee15fa9a9"
          },
          {
            "name": "Contract Count_Commission",
            "expression": "calculate(sum(TLDataSummary[ContractCount]),TLDataSummary[Revenue_Type]=\"commission revenue\")",
            "formatString": "0",
            "lineageTag": "b83759de-618e-4471-9bb4-23f30b8271b4"
          },
          {
            "name": "Avg Commission Rev per Contract",
            "expression": "If([Contract Count_Commission]=0,\"\",[Commission Revenue]/[Contract Count_Commission])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8d3f7511-30f2-4f3f-ba8c-23a6117ba6f5"
          },
          {
            "name": "Avg Admin Rev per Contract",
            "expression": "If([Contract Count_Admin]=0,\"\",[Admin Revenue]/[Contract Count_Admin])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c2e4f1f2-965c-4b24-bfae-1749d4634a15"
          },
          {
            "name": "Avg Rev per Contract",
            "expression": "If([Contract_Count]=0,\"\",[Total Revenue]/[Contract_Count])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "276f82ce-8847-4e92-97da-1cabfef13977"
          },
          {
            "name": "LTM Contract Count",
            "expression": [
              "",
              "",
              "VAR EndDate = MAX(DateCalendar[Date])",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [Contract_Count],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate)",
              ")",
              "",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "8f8e12f4-1f61-4c1c-ba39-a4c09ed01ccc"
          },
          {
            "name": "VSC Contract Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "calculate(sum(TLDataSummary[ContractCount]),TLDataSummary[Common_Product_Group]=\"VSC\")",
            "formatString": "0",
            "lineageTag": "a313faf5-4947-465e-83b0-504dc8058678"
          },
          {
            "name": "LTM VSC Contract Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR EndDate = MAX(DateCalendar[Date])",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [VSC Contract Count],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate)",
              ")",
              "",
              "RETURN",
              "    Result"
            ],
            "formatString": "0",
            "lineageTag": "9b7f05a0-2404-46aa-a346-71a7d7150442"
          },
          {
            "name": "LTM VSC % of Contract Count",
            "expression": "IFERROR([LTM VSC Contract Count]/[LTM Contract Count],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3f425c4b-f8d0-44df-bac2-6de1e7c8bff8"
          },
          {
            "name": "LTM Producing Rooftop Count",
            "expression": [
              "Calculate(",
              "    [Rooftop Count],",
              "    TLDataSummary[Revenue]>0)",
              "    +",
              "    0"
            ],
            "formatString": "0",
            "lineageTag": "d45d7da9-9b90-45ab-b067-40417c220524"
          },
          {
            "name": "LTM Rev per Rooftop",
            "expression": "[LTM Revenue V2]/[LTM Producing Rooftop Count]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b16ad44c-4bc3-463c-9a68-08b208463910"
          },
          {
            "name": "LTM Avg Rev per Contract",
            "expression": "If([Contract_Count]=0,\"\",[LTM Revenue V2]/[LTM Contract Count])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "38134938-298f-49b9-a58a-eb071c2f3a8e"
          },
          {
            "name": "LTM Admin Contract Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR EndDate = MAX(DateCalendar[Date])",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [Contract Count_Admin],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate)",
              ")",
              "",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "f712ecbb-7fa9-4db5-8565-185882db854c"
          },
          {
            "name": "LTM Comm Contract Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR EndDate = MAX(DateCalendar[Date])",
              "VAR StartDate = EDATE(EndDate, -12)",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    [Contract Count_Commission],",
              "    DATESBETWEEN(DateCalendar[Date], Startdate, Enddate)",
              ")",
              "",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "b49d07fa-5888-4d5b-a319-6cabc5e3dc87"
          },
          {
            "name": "LTM Avg Admin per Contract",
            "expression": "If([LTM Admin Contract Count]=0,\"\",[LTM Admin Revenue]/[LTM Admin Contract Count])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a6769494-1e8b-408f-a770-d0fdc45a203d"
          },
          {
            "name": "LTM Avg Comm per Contract",
            "expression": "If([LTM Comm Contract Count]=0,\"\",[LTM Commission Revenue]/[LTM Comm Contract Count])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "aa61f2dd-12f3-4abb-91d0-a67611aad5fb"
          },
          {
            "name": "MTD Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "TOTALMTD(sum(TLDataSummary[Revenue]),DateCalendar[Date],DATESMTD(DateCalendar[Date]))",
            "lineageTag": "9153c687-e31a-48d7-baaf-1267338292b4"
          },
          {
            "name": "Distance(KM)",
            "expression": [
              "",
              "Var lat1 = MIN('List of All U S  Counties and Cities'[lat])",
              "Var lng1 = MIN('List of All U S  Counties and Cities'[lng])",
              "",
              "Var lat2 = MIN(TLDataSummary[zip_lat])",
              "Var lng2 = MIN(TLDataSummary[zip_long])",
              "",
              "Var P = DIVIDE(PI(), 180)",
              "Var A = 0.5 - COS((lat2 - lat1) * P)/2 +",
              "        COS(lat1 * P) * COS(lat2 * P) * (1 - COS((lng2 - lng1) * P))/2",
              "Var final = ROUND(12742 * ASIN((SQRT(A))),0)",
              "Return",
              "final"
            ],
            "formatString": "0",
            "lineageTag": "8a44ff34-0739-4efb-8c7f-69930df6509b"
          },
          {
            "name": "isWithinThreshold",
            "expression": [
              "",
              "IF(",
              "    TLDataSummary[Distance(KM)] <= 'Maximum Distance'[Maximum Distance Value],",
              "    1,",
              "    0",
              ")"
            ],
            "lineageTag": "7804eed0-6aa0-4698-b79d-ff371d18d1e8"
          },
          {
            "name": "Map Point Size",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    TLDataSummary[Distance(KM)] <= 'Maximum Distance'[Maximum Distance Value],",
              "    IF(",
              "        HASONEFILTER('List of All U S  Counties and Cities'[City / County Name]),",
              "        SWITCH(",
              "            TRUE(),",
              "            TLDataSummary[Distance(KM)] = 0,",
              "            1,",
              "            0.25",
              "        ),",
              "    1",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "847b13a6-aead-44f1-9c54-34e767116128"
          },
          {
            "name": "Map Point Color",
            "expression": [
              "IF(HASONEFILTER('List of All U S  Counties and Cities'[City / County Name]),",
              " SWITCH(TRUE(),",
              " TLDataSummary[Distance(KM)] <= 'Maximum Distance'[Maximum Distance Value], \"#106A9E\", \"#FFFFFF\"))"
            ],
            "lineageTag": "861fdfac-18be-45dd-abde-694ada496e01"
          },
          {
            "name": "Sales_Rep_1 Count",
            "expression": "DISTINCTCOUNT(TLDataSummary[Sales_Rep_1])",
            "formatString": "0",
            "lineageTag": "11e6d422-fb9a-48a0-ad25-b4850dac3612"
          },
          {
            "name": "Num_Rooftop_Per_Rep",
            "expression": "ROUND([Rooftop Count]/[Sales_Rep_1 Count],0)",
            "formatString": "0",
            "lineageTag": "4e1d8a1f-2d9a-4aa6-9577-60a42adfe4e9"
          }
        ],
        "partitions": [
          {
            "name": "TLDataSummary-f2af69e2-f681-4d3d-bba5-6ff5d6771239",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"nacazsqlprfdbscus-01.database.windows.net\"),",
                "    TopLine = Source{[Name=\"TopLine\"]}[Data],",
                "    dbo_TLDataSummary = TopLine{[Schema=\"dbo\",Item=\"TLDataSummary\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_TLDataSummary,{{\"SaleYearMonth\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each Date.FromText(",
                "Text.Range([SaleYearMonth], 0,4) & \"-\"  &",
                "Text.Range([SaleYearMonth], 4,2)",
                ")),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Custom\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Custom\", \"Sale_Date\"}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns\", \"Latest Refresh\", each DateTime.FixedLocalNow),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom1\",{\"Latest Refresh\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Segmentation Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "664c5fad4c6f4d19ac91088bc9d33a38"
          }
        ],
        "columns": [
          {
            "name": "Segmentation Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "45c86257-62f8-4adc-931b-50c9729f6176",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Segmentation Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Segmentation Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Segmentation Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "06b0b044-6f57-4569-bfc9-2185d6ce480d",
            "sortByColumn": "Segmentation Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Segmentation Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "86c172d2-4a12-450f-9dac-c75b469e6496",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9282f671-1794-4bdb-abaf-c72dbdee140c",
        "partitions": [
          {
            "name": "Segmentation Parameter-6730ef3b-d322-45fd-8c1f-a4a83a672cd7",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Revenue_Type\", NAMEOF('TLDataSummary'[Revenue_Type]), 0),",
                "    (\"BusinessUnit\", NAMEOF('TLDataSummary'[BusinessUnit]), 1),",
                "    (\"SalesChannel\", NAMEOF('TLDataSummary'[SalesChannel]), 2),",
                "    --(\"Product_Grouping_Pricing_Cancel_Analysis\", NAMEOF('TLDataSummary'[Product_Grouping_Pricing_Cancel_Analysis]), 3),",
                "    (\"Common_Product_Group\", NAMEOF('TLDataSummary'[Common_Product_Group]), 4),",
                "    (\"Rooftop_State\", NAMEOF('TLDataSummary'[Rooftop_State]), 5),",
                "    (\"Rooftop_City\", NAMEOF('TLDataSummary'[Rooftop_City]), 6),",
                "    (\"Agent_Group_Name\", NAMEOF('TLDataSummary'[Agent_Group_Name]), 7),",
                "    (\"Dealer_Group_Name\", NAMEOF('TLDataSummary'[Dealer_Group_Name]), 8),",
                "    (\"Administrator\", NAMEOF('TLDataSummary'[Administrator]), 9),",
                "    (\"Rooftop_Name\", NAMEOF('TLDataSummary'[Rooftop_Name]), 10),",
                "    (\"TransactionTypeDesc\", NAMEOF('TLDataSummary'[TransactionTypeDesc]), 11),",
                "    (\"End_Market\", NAMEOF('TLDataSummary'[End_Market]), 12),",
                "    (\"Region\", NAMEOF('TLDataSummary'[Region]), 13),",
                "   (\"Area\", NAMEOF('TLDataSummary'[Area_Director]), 14),",
                "   (\"Sales_Rep\", NAMEOF(TLDataSummary[Sales_Rep_1]), 15),",
                "   (\"DealerName\", NAMEOF(TLDataSummary[DealerName]), 15)}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DateCalendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d41ad8d4096e4dcf892c6a0e1aab1072"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"DateCalendar\",\"TableItemName\":\"Date (bins)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "8998067d-8c2d-47ba-955b-2b866007a8b2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "Year([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a3a86d89-5c5a-4571-8ba3-e4a39e3613f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "Month([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "df928ddd-3b00-40eb-bc50-daed16b25000",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FutureDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "DateCalendar[Date]>Today()",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "98d70861-d1ec-4512-bf13-f7aea1593694",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Relative Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "12 * Year([Date]) ",
              "+ ",
              "Month([Date]) ",
              "- ",
              "12 * Year(Today()) ",
              "- ",
              "Month(Today())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b9dcb184-d76a-4c6e-9f81-9eb7123ed075",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date (bins)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"d\",\"Entity\":\"DateCalendar\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Date\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Date\"}},\"Size\":1.0,\"TimeUnit\":2}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "\tISBLANK('DateCalendar'[Date]),",
              "\tBLANK(),",
              "\tDATE(",
              "\t\tYEAR('DateCalendar'[Date]),",
              "\t\t1 + (MONTH('DateCalendar'[Date]) - 1),",
              "\t\t1",
              "\t)",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 6,
                      "value": 1.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "DateCalendar"
                          }
                        },
                        "Property": "Date"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "Short Date",
            "lineageTag": "682d3196-0be5-4771-983c-d39332e7e342",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Period Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(DateCalendar[Month] = 12,\"FY\" & RIGHT(FORMAT(DateCalendar[Year], \"General Number\"),2),IF(AND(DateCalendar[Month]=MONTH(  DATE ( YEAR ( TODAY () ), MONTH ( TODAY () ) - 2, DAY ( TODAY () ) )),DateCalendar[Year]=YEAR(  DATE ( YEAR ( TODAY () ), MONTH ( TODAY () ) - 2, DAY ( TODAY () ) ))),\"LTM \" & FORMAT(DateCalendar[Date],\"MMM\") & \"-\" & RIGHT(FORMAT(DateCalendar[Year], \"General Number\"),2), \"\"))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d5274db8-b999-4bfa-ad43-8a3cf26fd5ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Period Label V2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(DateCalendar[Month] = 12,\"FY\" & RIGHT(FORMAT(DateCalendar[Year], \"General Number\"),2),IF(AND(DateCalendar[Month]=MONTH(EDATE(Today(),-1)) ,DateCalendar[Year]=YEAR(EDATE(TODAY(),-1))),\"LTM \" & FORMAT(DateCalendar[Date],\"MMM\") & \"-\" & RIGHT(FORMAT(DateCalendar[Year], \"General Number\"),2), IF(AND(DateCalendar[Month]=MONTH(EDATE(Today(),-1)) ,DateCalendar[Year]=YEAR(EDATE(TODAY(),-1))),\"LTM \" & FORMAT(DateCalendar[Date],\"MMM\") & \"-\" & RIGHT(FORMAT(DateCalendar[Year], \"General Number\"),2),\"\")))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "aacbf300-8957-47da-be2b-bc73ed16586f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Months for Inclusion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "ABS(DateCalendar[Relative Month])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6fc952b3-be66-4278-9a14-5a867c9ab20d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "EmptyFilter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF(",
              "(CALCULATE(",
              "    [Total Revenue],",
              "    ALLEXCEPT('DateCalendar', 'DateCalendar'[Date (bins)])",
              "    ",
              "",
              ")) > 0,",
              "1,",
              "0",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6f90454e-5834-41a2-bd95-69654ab499a6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "94a624d5-172f-482d-b54c-e2a4642a36b6",
        "partitions": [
          {
            "name": "DateCalendar-c7fd4571-e997-4ff6-b352-993be3abd6eb",
            "mode": "import",
            "source": {
              "expression": "Filter(CALENDARAUTO(),[Date]<=Today())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Number of Months to Include",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d7dbb8e1fab647449153adac0d297471"
          }
        ],
        "columns": [
          {
            "name": "Number of Months to Include",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8ce2c1a7-7538-404c-b203-071b921e7f37",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2f40093f-1129-4d19-ad72-84b93422a10a",
        "measures": [
          {
            "name": "Number of Months to Include Value",
            "expression": "SELECTEDVALUE('Number of Months to Include'[Number of Months to Include], 12)",
            "formatString": "0",
            "lineageTag": "26a0bd58-639d-4b8b-b524-6e2943927738"
          }
        ],
        "partitions": [
          {
            "name": "Number of Months to Include-21674bea-7494-46f6-b568-3ab3a0b919bf",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 48, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Last Refresh Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UTC Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "abc1401a-48b0-4c3b-8238-4a236109dead",
            "sourceColumn": "UTC Time",
            "summarizeBy": "none"
          },
          {
            "name": "Eastern Conversion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5f285126-81cc-439a-b3d1-8f0407dd0af5",
            "sourceColumn": "Eastern Conversion",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dc11c511-8515-40ed-8e08-272e75775de7",
        "partitions": [
          {
            "name": "Last Refresh Date-dabb10a5-76ad-420c-a5ae-5b9405a88621",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.LocalNow(),",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\",{{\"Column1\", type datetime}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"LocalDateTime\", each DateTime.AddZone([Column1],5)),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Column1\", \"UTC Time\"}, {\"LocalDateTime\", \"Eastern Conversion\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Eastern Conversion\", type datetime}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "434cc23f3d91495da2522ce0be2e1a67"
          }
        ],
        "columns": [
          {
            "name": "KPI Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "2139d2c0-c1c2-4728-ab02-5c1019c14332",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "KPI Parameter Fields"
                }
              ]
            },
            "sortByColumn": "KPI Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KPI Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "c33d9275-1765-4af2-aa52-469ed9b58804",
            "sortByColumn": "KPI Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KPI Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dee419ce-2342-4504-9a4a-de0950ddb95a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4dd0af4d-c963-4446-8d62-5e192c6c09d1",
        "partitions": [
          {
            "name": "KPI Parameter-258898a8-3471-40a4-8dd4-57dff801dc3e",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Revenue\", NAMEOF('TLDataSummary'[Total Revenue]), 0),",
                "    (\"Net Count\", NAMEOF([Contract_Count]), 1),",
                "    (\"Dealer Count\", NAMEOF('TLDataSummary'[Dealer Count]), 2),",
                "    (\"Rooftop Count\", NAMEOF('TLDataSummary'[Rooftop Count]), 3),",
                "    (\"Revenue Per Rooftop\", NAMEOF('TLDataSummary'[Revenue Per Rooftop]), 4)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "XREF_DealerGrps",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8d33cc4-fe90-4698-b812-d0d551c645c6",
            "sourceColumn": "dealer_id",
            "summarizeBy": "sum"
          },
          {
            "name": "datasource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5da41853-0054-42b4-89d6-c4ae4d9a7a01",
            "sourceColumn": "datasource",
            "summarizeBy": "none"
          },
          {
            "name": "Dealer_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d5d1d15-e947-4a02-9bb4-897ad5f44c4f",
            "sourceColumn": "Dealer_number",
            "summarizeBy": "none"
          },
          {
            "name": "Dealer_Name_original",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bc2a43e-9dd7-40a5-9baf-32b1fd2c5330",
            "sourceColumn": "Dealer_Name_original",
            "summarizeBy": "none"
          },
          {
            "name": "Dealer_Group_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebc19478-c319-4aa5-8d8b-ad6f53c36cbe",
            "sourceColumn": "Dealer_Group_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7ac38de-a101-450e-a280-1a4b3e584ce0",
            "sourceColumn": "Rooftop_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_Addr_Original",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "928e0539-bccf-4942-ab5a-5046ea86901a",
            "sourceColumn": "Rooftop_Addr_Original",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_Addr_Updated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b3aaffc-8ba0-47a5-8a3e-60d500a35a7e",
            "sourceColumn": "Rooftop_Addr_Updated",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e776f6e-d9bc-4900-b806-f649c96e8732",
            "sourceColumn": "Rooftop_City",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42b5593c-3634-4429-bf63-20bdba89cf25",
            "sourceColumn": "Rooftop_State",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_Zip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a9f8e6a-2bae-4be6-894b-791d1eecc6f1",
            "sourceColumn": "Rooftop_Zip",
            "summarizeBy": "none"
          },
          {
            "name": "Franchise_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3befe30-6cdb-4b00-8e01-8dd64d85344b",
            "sourceColumn": "Franchise_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7042beb1-f1d4-4587-839f-c86dcd8dbfdd",
            "sourceColumn": "Sales_Rep",
            "summarizeBy": "none"
          },
          {
            "name": "Flag_Bank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a72f657c-4d7c-41ef-8086-9947ac50185c",
            "sourceColumn": "Flag_Bank",
            "summarizeBy": "none"
          },
          {
            "name": "Flag_Credit_Union",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f30112eb-7f53-463d-b032-867bdd6217fc",
            "sourceColumn": "Flag_Credit_Union",
            "summarizeBy": "none"
          },
          {
            "name": "Flag_Refinance_Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3f4a3cc7-3062-4be0-99fb-ef5d3f53c745",
            "sourceColumn": "Flag_Refinance_Company",
            "summarizeBy": "none"
          },
          {
            "name": "dtupdate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "fba3b3e2-52e0-4f7f-9af6-8fba9aadee8c",
            "sourceColumn": "dtupdate",
            "summarizeBy": "none"
          },
          {
            "name": "ENDMARKET",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee86146b-71c5-4fb1-8417-2f53decea084",
            "sourceColumn": "ENDMARKET",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bc8c17a-b5c7-45ca-9720-3bd116fa9add",
            "sourceColumn": "Sales_Rep_1",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7310d106-baee-46dd-83ae-e9a82605bece",
            "sourceColumn": "Sales_Rep_2",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffa84350-668d-4e83-bdf2-d591df121039",
            "sourceColumn": "Sales_Rep_3",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12d15efe-0cc9-4649-8f15-dedcef3116dc",
            "sourceColumn": "Sales_Rep_4",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Rep_1_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b423d991-7c94-4153-86a9-e731f9aa8616",
            "sourceColumn": "Sales_Rep_1_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rep_2_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e7597cff-258a-4b0a-8a0f-66a947729a69",
            "sourceColumn": "Sales_Rep_2_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rep_3_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "de4eee5c-e085-4677-bcb8-4cb288801362",
            "sourceColumn": "Sales_Rep_3_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rep_4_Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c510c34e-892a-4a38-bcc4-3c2330249d86",
            "sourceColumn": "Sales_Rep_4_Pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Area_Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf564a96-5a14-41b0-add0-915a82ee7709",
            "sourceColumn": "Area_Director",
            "summarizeBy": "none"
          },
          {
            "name": "Regional_Vice_President",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba33d996-d5c5-47a1-821a-bd8709817de7",
            "sourceColumn": "Regional_Vice_President",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35a90a49-fbc1-4e16-a69b-3e83f758a30a",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Active_Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d11a908-121e-4c61-9a88-4a1a309f0eee",
            "sourceColumn": "Sales_Active_Flag",
            "summarizeBy": "none"
          },
          {
            "name": "ParentKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d6f4df4-97c2-49ad-b033-316edd4cb550",
            "sourceColumn": "ParentKey",
            "summarizeBy": "count"
          },
          {
            "name": "Sales_Channel_Assignment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3a68eb3-234c-413a-aa82-76a6219095f7",
            "sourceColumn": "Sales_Channel_Assignment",
            "summarizeBy": "none"
          },
          {
            "name": "Rooftop_State_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d2b64a2-839c-4a0b-bd39-d3b1b4f5188f",
            "sourceColumn": "Rooftop_State_Name",
            "summarizeBy": "none"
          },
          {
            "name": "zip_lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8bed1de0-92e9-4fb2-9330-1c19b91e1c1c",
            "sourceColumn": "zip_lat",
            "summarizeBy": "sum"
          },
          {
            "name": "zip_long",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "645a666c-b925-4a93-8865-e2fe4226fcd2",
            "sourceColumn": "zip_long",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "20421ccd-8f53-4db1-9a6e-f86e24ce4894",
        "partitions": [
          {
            "name": "XREF_DealerGrps-3cc39d30-4be4-4052-9e62-07e77a3c9a16",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"nacazsqlprfdbscus-01.database.windows.net\"),",
                "    TopLine = Source{[Name=\"TopLine\"]}[Data],",
                "    dbo_XREF_DealerGrps = TopLine{[Schema=\"dbo\",Item=\"XREF_DealerGrps\"]}[Data]",
                "in",
                "    dbo_XREF_DealerGrps"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ZipCode_SQLDb",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "zip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "71d31237-2ee7-486b-a5a7-c9ff4598effa",
            "sourceColumn": "zip",
            "summarizeBy": "sum"
          },
          {
            "name": "lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d1712527-8b45-43c4-95a9-ae7e3f4c1968",
            "sourceColumn": "lat",
            "summarizeBy": "sum"
          },
          {
            "name": "lng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f37875d9-259a-413e-bda9-8ce1a693154b",
            "sourceColumn": "lng",
            "summarizeBy": "sum"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d61d72c6-9521-4b92-9155-e2598a892e5e",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "state_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b966d306-1460-4b5f-ac5b-6a879f6dabec",
            "sourceColumn": "state_id",
            "summarizeBy": "none"
          },
          {
            "name": "state_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23b244a1-ec14-4265-873f-e8c78ea830e3",
            "sourceColumn": "state_name",
            "summarizeBy": "none"
          },
          {
            "name": "population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "b2da6fcb-7a49-402e-af83-6dc5fba19a43",
            "sourceColumn": "population",
            "summarizeBy": "sum"
          },
          {
            "name": "county_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4f1dada-3c6f-4085-9abf-2474ef53886a",
            "sourceColumn": "county_name",
            "summarizeBy": "none"
          },
          {
            "name": "county_fips_all",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9432c017-72d7-4dca-8515-0fd5b4fcaab2",
            "sourceColumn": "county_fips_all",
            "summarizeBy": "none"
          },
          {
            "name": "timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3397988-0e34-4498-a362-1431a930b2ba",
            "sourceColumn": "timezone",
            "summarizeBy": "none"
          },
          {
            "name": "Zip_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if(len([zip])=3,\"00\" & [zip],if(len([zip])=4,\"0\" & [zip],Left([zip],5)))",
            "isDataTypeInferred": true,
            "lineageTag": "e3229f62-9c46-4811-8876-4208f4c83290",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "zcta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1d8972e2-f763-41f6-bb4b-ad61fed6924a",
            "sourceColumn": "zcta",
            "summarizeBy": "none"
          },
          {
            "name": "parent_zcta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b5205c6e-2522-455e-b985-22d275aa4525",
            "sourceColumn": "parent_zcta",
            "summarizeBy": "sum"
          },
          {
            "name": "density",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "895f4096-b8dc-42d5-8ca1-8068cf5568ad",
            "sourceColumn": "density",
            "summarizeBy": "sum"
          },
          {
            "name": "county_fips",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5e0431f-6b12-4a46-93fb-f5d815836220",
            "sourceColumn": "county_fips",
            "summarizeBy": "sum"
          },
          {
            "name": "county_weights",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39b21fd2-ff8b-403f-a735-d6f587d6cc0e",
            "sourceColumn": "county_weights",
            "summarizeBy": "none"
          },
          {
            "name": "county_names_all",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b5316fa-df68-44f6-bb67-8b30c9029d32",
            "sourceColumn": "county_names_all",
            "summarizeBy": "none"
          },
          {
            "name": "imprecise",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "48a349ef-50b7-4bc0-aedd-924a37c2e681",
            "sourceColumn": "imprecise",
            "summarizeBy": "none"
          },
          {
            "name": "military",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c885e23e-ae71-47dc-8a64-38df4e395125",
            "sourceColumn": "military",
            "summarizeBy": "none"
          },
          {
            "name": "age_median",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a9c27746-7639-4fae-b9f5-79e8bbd74f52",
            "sourceColumn": "age_median",
            "summarizeBy": "sum"
          },
          {
            "name": "male",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2e771f4-b03b-4770-8165-778f6105f414",
            "sourceColumn": "male",
            "summarizeBy": "sum"
          },
          {
            "name": "female",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6d017e36-1137-4834-9662-b05d1013af99",
            "sourceColumn": "female",
            "summarizeBy": "sum"
          },
          {
            "name": "married",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad7e40ab-35ce-410b-928e-b46c10da6da1",
            "sourceColumn": "married",
            "summarizeBy": "sum"
          },
          {
            "name": "family_size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4d4875de-2a91-474c-b85d-05daf9ef147c",
            "sourceColumn": "family_size",
            "summarizeBy": "sum"
          },
          {
            "name": "income_household_median",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f7044b6c-ecfa-4e90-a51d-2e102f56dc4a",
            "sourceColumn": "income_household_median",
            "summarizeBy": "sum"
          },
          {
            "name": "income_household_six_figure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0481bbf-3c63-4561-abcd-c8ff9b952cd0",
            "sourceColumn": "income_household_six_figure",
            "summarizeBy": "sum"
          },
          {
            "name": "home_ownership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "634b50f6-e1e6-4d06-9699-998c46b8ff28",
            "sourceColumn": "home_ownership",
            "summarizeBy": "sum"
          },
          {
            "name": "home_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9b3d486a-b941-469d-a9cf-4fbb12ad8fd0",
            "sourceColumn": "home_value",
            "summarizeBy": "sum"
          },
          {
            "name": "rent_median",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7080937b-fb69-4b74-b242-15f27c43aa04",
            "sourceColumn": "rent_median",
            "summarizeBy": "sum"
          },
          {
            "name": "education_college_or_above",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7f2757fc-6c65-49e4-98be-28bb703688d9",
            "sourceColumn": "education_college_or_above",
            "summarizeBy": "sum"
          },
          {
            "name": "labor_force_participation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7f71a365-0cc1-4d58-a66c-9b38d48015a0",
            "sourceColumn": "labor_force_participation",
            "summarizeBy": "sum"
          },
          {
            "name": "unemployment_rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c7919732-962d-4c8a-a91e-07e1f91bb33c",
            "sourceColumn": "unemployment_rate",
            "summarizeBy": "sum"
          },
          {
            "name": "race_white",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "26b01a51-6928-41dd-893c-4219bd1bb7b2",
            "sourceColumn": "race_white",
            "summarizeBy": "sum"
          },
          {
            "name": "race_black",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f256087a-c56c-4b0f-ab1e-f9c5b1986f8b",
            "sourceColumn": "race_black",
            "summarizeBy": "sum"
          },
          {
            "name": "race_asian",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8c8f78f3-dad5-440a-89cf-b5dc9c6c721b",
            "sourceColumn": "race_asian",
            "summarizeBy": "sum"
          },
          {
            "name": "race_native",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8333a1a7-3364-4478-be73-b157c01f1e83",
            "sourceColumn": "race_native",
            "summarizeBy": "sum"
          },
          {
            "name": "race_pacific",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "89277662-bb7d-4745-abcb-56b9fa3774ed",
            "sourceColumn": "race_pacific",
            "summarizeBy": "sum"
          },
          {
            "name": "race_other",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9924b31-3bc8-4841-98a5-c7623cead8e5",
            "sourceColumn": "race_other",
            "summarizeBy": "sum"
          },
          {
            "name": "race_multiple",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2f86558a-24ac-4c29-9e7b-e9fb705adc36",
            "sourceColumn": "race_multiple",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e4f98df0-32e4-44bd-a084-83d93af2e0cb",
        "partitions": [
          {
            "name": "ZipCode_SQLDb-89c6b714-79ec-4322-a6c3-b94563527c1f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"APCO_EDW_PR1.APCO.COM\", \"EDW\", [Query=\"Select *#(lf)From mapping.geography\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Maximum Distance",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "611f680d929147548099e7c41f53ea47"
          }
        ],
        "columns": [
          {
            "name": "Maximum Distance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "c7060b9f-977f-49bf-8997-e66a3e1fd199",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "dc59e46c-6ff1-4ddf-92f2-dd738a8864fd",
        "measures": [
          {
            "name": "Maximum Distance Value",
            "expression": "SELECTEDVALUE('Maximum Distance'[Maximum Distance])",
            "formatString": "0",
            "lineageTag": "48684305-bfa2-4acb-bc31-206da6cc4563"
          }
        ],
        "partitions": [
          {
            "name": "Maximum Distance",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 50, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "List of All U S  Counties and Cities",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City / County Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5886c4e7-11d6-4ace-8df3-3bd425fdd15d",
            "sourceColumn": "City / County Name",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb796e77-50fd-498c-bc9f-8778b4e41cc7",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67572f01-f867-40bd-84a7-b7fcecc59ba5",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "State Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9394a485-77e5-4c58-b8bf-fecfdfadb4e7",
            "sourceColumn": "State Name",
            "summarizeBy": "none"
          },
          {
            "name": "County",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38bd4367-bc88-4ecd-800c-bdb4bdc84809",
            "sourceColumn": "County",
            "summarizeBy": "none"
          },
          {
            "name": "lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7812cad6-7d8b-41b4-986f-6e7839ddf192",
            "sourceColumn": "lat",
            "summarizeBy": "sum"
          },
          {
            "name": "lng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e53597e1-1f08-4fba-b1ee-6094c8ed1054",
            "sourceColumn": "lng",
            "summarizeBy": "sum"
          },
          {
            "name": "population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d74b7c8c-61c4-42e9-95a0-e1acbda9b43f",
            "sourceColumn": "population",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9ce25a0f-9a0f-41b3-9e91-34ade1d46ea7",
        "partitions": [
          {
            "name": "List of All U S  Counties and Cities",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\manoj.sharma\\Desktop\\Apco DA Research initiative\\List of All U.S. Counties and Cities.csv\"),[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"City / County Name\", type text}, {\"Type\", type text}, {\"State\", type text}, {\"State Name\", type text}, {\"County\", type text}, {\"lat\", type number}, {\"lng\", type number}, {\"population\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}